### PR TITLE
setup of the project

### PR DESCRIPTION
**Pull request by keewis**
This adds a `pyproject.toml` (see [What the heck is pyproject.toml](https://snarky.ca/what-the-heck-is-pyproject-toml/) for its purpose) and moves the metadata from `setup.py` to `setup.cfg`. With that, the only reason we still need `setup.py` is for editable installs (`python -m pip install -e .`).

For versions, both `pint` and `xarray` rely on `setuptools_scm`, which uses the repository's tags to provide a version. Should we use it, too?

### CODE REVIEW

**Comment by TomNicholas** [comment]
> This adds a pyproject.toml (see What the heck is pyproject.toml for its purpose)

Thank you for this. I haven't really set up all the CI and versioning stuff from scratch before, so I appreciate your help.

> uses the repository's tags to provide a version

That sounds good, but where do we set the tags?

Separately, I've added tests with azure (copying xarray), but I'm having 2 issues:
1) Black formatting is creating code that flake8 doesn't like, but I guess I'll just remove the flake8 check.
2) The python3.8 checks are failing
3) It's currently downloading the test environments using pip but I guess we should use conda? pip is currently pointing to Pint's master branch too.

**Comment by keewis** [comment]
Tags are a `git` feature (mostly used for releasing). See `xarray`'s `HOW_TO_RELEASE.md` file for an example.

> black formatting is creating code that flake8 doesn't like

we can set ignores in `setup.cfg` (or `pyproject.toml`?). `xarray` has quite a list of ignores, we can go through each of them and see if that works out.

> The python3.8 checks are failing

That's because there does not seem to be a py38 wheel for python, yet. We could switch to `conda`, which does not have that problem (though it is a bit slower than `pip` with wheels). Installing from github is possible with the `pip` section in `conda`'s environment files.

Also, could you add a upstream-dev CI? It is really useful as a early warning system for breaking changes in the dependencies.

**Comment by keewis** [comment]
also, for the CI setup: since he did the setup for `xarray`, maybe @shoyer can guide you with that?

**Comment by keewis** [comment]
okay, now `flake8` and `black` don't complain anymore and running `python setup.py sdist bdist_wheel` works, too

Should we merge this?

**Comment by keewis** [comment]
gentle ping, @TomNicholas

**Comment by TomNicholas** [comment]
Thanks @keewis, this looks okay to me, if you're happy with this working do you want to just merge it and we can add other features like an upstream-dev CI in later?

**Comment by keewis** [comment]
yes, that's fine.

**Comment by keewis** [comment]
before I merge: what should be our preferred merge option? Github offers normal merge, squash merge and rebase merge. To keep a linear history on master, squash merge is the simplest but some history is lost (not sure if that's important, though).

If we decide on one, could you disable the others so accidentally using another option is impossible?

**Comment by TomNicholas** [comment]
Great. I vote squash merge, as it's works well for xarray, and I've never seen an example where I would have preferred to keep that history. I'll disable the others now.

**Comment by keewis** [comment]
thanks, @TomNicholas

**Pull request merged**
