### PR TITLE
initial documentation

### PR DESCRIPTION
**Pull request by keewis**
Initial skeleton of the documentation. I'm using my (unreleased) [sphinx-autosummary-accessors](https://github.com/keewis/sphinx-autosummary-accessors) project to format the accessor pages properly, which seems to work just fine.

### CODE REVIEW

**Comment by keewis** [comment]
It seems we need to merge this before we can get PR builds with RTD.

@TomNicholas: The only thing I'd need you to review for now is the use of `sphinx-autosummary-accessors`. That project is close enough so I can't see much harm in installing it from github.

**Comment by keewis** [comment]
merging. If there's something wrong, we can always open a new PR.

**Comment by keewis** [comment]
actually, it seems RTD didn't trigger because it didn't receive any authentication for the webhook.

@TomNicholas: what do you think about moving this to a different organization, e.g. `xarray-contrib`?

**Comment by TomNicholas** [comment]
Thanks for this!

> what do you think about moving this to a different organization, e.g. xarray-contrib?

I'm happy for it to live anywhere. Seeing that `xarray-contrib` now contains [cf-xarray](https://github.com/xarray-contrib/cf-xarray), then it seems like a good place? My only question would be how do the permissions work then? We probably want to give access to people already in xarray-contrib and any of the pint contributors/people contributing here who are interested.

**Comment by keewis** [comment]
That should be possible. All members of an organization automatically have access (`Member`), and we can also invite people to maintain a single repository (`Collaborator`).

**Comment by TomNicholas** [comment]
Okay, in that case I suggest we ask about it in the xarray community meeting this afternoon.

**Comment by TomNicholas** [comment]
> Okay, in that case I suggest we ask about it in the xarray community meeting this afternoon.

"Yes please!" said Stephan. I'll see if I can do that now.

**Comment by TomNicholas** [comment]
@keewis I just moved it - access seems to be as expected. I also sent an invite to @jthielen for write access

**Comment by jthielen** [comment]
@TomNicholas Got it, thanks!

**Pull request merged**
